[package]
name = "sgx-scroll-enclave"
version.workspace = true
edition.workspace = true

[features]
tstd_app = ["automata-sgx-sdk/tstd_app"]

[package.metadata.sgx]
app_enclave = { path = "../../crates/app-enclave", config = "sgx/config.xml", edl = "sgx/enclave.edl", lds = "sgx/enclave.lds", key = "sgx/private.pem", env = ["PKG_CONFIG_ALLOW_CROSS=1"] }

[dependencies]
automata-sgx-sdk.workspace = true
serde_json.workspace = true
serde.workspace = true

[build-dependencies]
automata-build-script.workspace = true